# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4318434591a9614087427fa03f0750e82a6a2504bd73fcd797ed8508e69578bab7670bac3a1cdf914c6326e8c06932339c24e81614a63152cb5ac7943899ab

test:
  secret_key_base: e1c74c7b7400209f71fd425b90fa402005125aebcb7597923337b61aebcda531a9770fba393730c11ab4509e4f3a3d10db5cb495508c6bcb5c526f5b3c8a6bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
